# Generated by Django 4.2.11 on 2024-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('staff', 'STAFF'), ('parent', 'PARENT')], max_length=20),
        ),
    ]
